### ISSUE TITLE
Possibility to change global props after init

### ISSUE THREAD

**Issue by memic84** [mazipan/vue-currency-filter#13]
I am using VueI18n with three languages, and i cannot change the global props of the CurrencyFilter plugin, when i change a language.

I don't want to put all the config inline for every time i use it, but instead i want to do something like.
`this.$currencyFilter= {}` in my method for changing language.

Is this possible?

This is my code
**main.js**
```
import VueCurrencyFilter from 'vue-currency-filter'

Vue.use(VueCurrencyFilter,
    {
        symbol : '€',
        thousandsSeparator: '.',
        fractionCount: 2,
        fractionSeparator: ',',
        symbolPosition: 'front',
        symbolSpacing: true
    });
```

I would need to override symbol, thousandsSeparator and fractionSeparator

**Comment by mazipan** [comment]
I think it's hard for now, because in `Vue.use` we only using it once.
It only using when initialization for default value.
We can watch any changes in this configuration.
have no idea yet.

But I will keep this issue open, if there is anyone that have good approach.
Thanks anyway @memic84

**Comment by mazipan** [comment]
I add this methods

```js
this.$CurrencyFilter.setConfig(newConfigs)
```

from v3.1.0.

**Comment by memic84** [comment]
Nice! Thanks @mazipan
