### ISSUE TITLE
Values are not well rounded

### ISSUE THREAD

**Issue by Roywcm** [mazipan/vue-currency-filter#15]
Hi,

Rounding values with 3 decimals is not working properly. 
When I have a value e.g. 9.075. It round's to 9.07 and not 7.08.

**Comment by mazipan** [comment]
Can you give me sample configuration that you used @Roywcm ?

**Comment by Roywcm** [comment]
Actually, it's also accuring in your demo: https://mazipan.github.io/vue-currency-filter/ :)

My configuration is:
```
Vue.use(VueCurrencyFilter,{
    symbol : '€',
    thousandsSeparator: '.',
    fractionCount: 2,
    fractionSeparator: ',',
    symbolPosition: 'front',
    symbolSpacing: true
});
```

**Comment by mazipan** [comment]
Has been opened issue in accounting.js 

https://github.com/openexchangerates/accounting.js/issues/195

I will help to investigate, is this coming from accounting.js or wrong usage from this library.

**Comment by mazipan** [comment]
![screen shot 2018-05-15 at 5 41 57 pm](https://user-images.githubusercontent.com/7221389/40052145-54bb6efa-5867-11e8-9c50-6446921ab8f3.png)

**Comment by mazipan** [comment]
Close in version **2.1.2**
