### ISSUE TITLE
New Logo For vue-currency-filter

### ISSUE THREAD

**Issue by iqbalhood** [mazipan/vue-currency-filter#19]
Hallo @mazipan , Saya Iqbal dari Medan. Boleh nggak saya kontribusi ngebuatin logo untuk vue currency filter buatan @mazipan ?

**Comment by iqbalhood** [comment]
Oke Mas Segera Dibuatkan :) 👍

**Comment by iqbalhood** [comment]
Hallo @mazipan, Berikut ini adalah logo proposal saya untuk proyek ini , Bila ada  yang perlu diperbaiki atau revisisi mohon diberi tahu. 

![vue](https://user-images.githubusercontent.com/1563756/40868801-f678fbd2-663a-11e8-8fc8-ec25876ce215.jpeg)
![vue2](https://user-images.githubusercontent.com/1563756/40868802-f6b3701e-663a-11e8-90ad-044af6489381.jpeg)

**Comment by mazipan** [comment]
Saya sih gak ada masalah mas, oke kok saya mah.
Yang orange sih keren kayanya mas @iqbalhood.

Cuma minta bantuan ya mas, mungkin minta di provide beberapa versi image kaya PNG dan SVG nya.
Untuk PNG kalo bisa minta ukuran 128, 192 sama 512.


Terima kasih 🙏
Maaf merepotkan 😅

**Comment by iqbalhood** [comment]
Oke mas no problem, Segera dikerjakan :)  Terima kasih Kembali 🙏

**Comment by iqbalhood** [comment]
Hallo @mazipan , ini file logo yang tadi di request. Kabarin ya mas kalau sudah masuk Readme.md proyek ini. Makasih 😊
https://drive.google.com/drive/folders/1YlCiuReB640oxg0PKFCCBNiAG5LfIIsy?usp=sharing

**Comment by mazipan** [comment]
Siap mas @iqbalhood, nanti bisa di track di issue #22 ya.

**Comment by iqbalhood** [comment]
Siap @mazipan , Makasih 👍

**Comment by mazipan** [comment]
Done ya mas @iqbalhood 

terima kasih banyak loh...
kapan2 boleh lagi loh 🤣

**Comment by iqbalhood** [comment]
Oke siap mas @mazipan :)
