### ISSUE TITLE
Non decimal suffix option

### ISSUE THREAD

**Issue by carrera** [mazipan/vue-currency-filter#190]
Currently in the module it shows 49,00 but it would be nice if there was an option so it could show 49,- since this is the way its shown in euro's

**Comment by mazipan** [comment]
@carrera, you can pass config:

```js
{
      symbol: ',-', // use ,- as a symbol
      thousandsSeparator: ',',
      fractionCount: 0,
      fractionSeparator: '.',
      symbolPosition: 'end', // move symbol to the end
      symbolSpacing: false // remove space
}
```

**Comment by carrera** [comment]
Yeah but the thing with that is only with round numbers it is € 49,- while with non round numbers it is € 49,50

**Comment by mazipan** [comment]
Just set fraction to 2 if you want have a fraction.

**Comment by carrera** [comment]
Okay but where is the currency symbol with this config

**Comment by mazipan** [comment]
Pull requests are welcome if you think you need additional parameter to solve your case.

**Comment by carrera** [comment]
Okay i'll look into it

**Comment by niccord** [comment]
You can achieve what you ask by using version `5.2.0` passing `avoidEmptyDecimals: '-'` in the config object.
