### ISSUE TITLE
How to use non-breaking spaces ?

### ISSUE THREAD

**Issue by gelambert** [mazipan/vue-currency-filter#198]
I would like to use non-breaking spaces (`&nbsp;` in HTML) to format a price (for example 1 337,00 €).

I can inject it using `thousandsSeparator`.

However, it is not possible for the space before the symbol.
Could you add a parameter called `symbolSeparator` to make it possible ?

**Comment by mazipan** [comment]
So what string do you want to achieve?
Is this `337,00 €`?
Also how you achieve this for now?

`symbolSeparator` is not common from my perspective.

**Comment by gelambert** [comment]
@mazipan ,

> So which string do you want to achieve @gelambert ?
> Is this 337,00 €?

I want to achieve `1&nbsp;337,00&nbsp;€` instead of `1 337,00 €`.

> Also how you achieve this for now?

I am using CSS (`white-space: nowrap`) but it would be easier for me to handle it with Vue Currency Filter !

---

I want the amount to continue on the same line.
For example :

- with breaking spaces

![image](https://user-images.githubusercontent.com/13656633/81833417-f5f25880-953f-11ea-83c7-5687779d164f.png)

- with non-breaking spaces

![image](https://user-images.githubusercontent.com/13656633/81833471-0d314600-9540-11ea-83de-106af71b3618.png)

I hope I'm clear !

**Comment by mazipan** [comment]
Actually you can achieve this with adding one layer filter after `vue-currency-filter`.
This is better solution if you prefer modify the value instead of using CSS.

Example create a simple global filter:

```js
Vue.filter('useHtmlSpace', function(value) {
  return value.replace(/\s/g, '&nbsp;');
});
```

Example create local filter inside component:

```js
filters: { 
  useHtmlSpace: function (value) {
    return value.replace(/\s/g, '&nbsp;');
  }
 }
```

Usage: 

```js
{{ value | currency | useHtmlSpace }}
```

**Comment by gelambert** [comment]
This a nice workaround.
However, it will render `&nbsp;` as text so I would use a Unicode :
```
Vue.filter( 'useHtmlSpace', function ( value: string ) {
    return value.replace( /\s/g, '\u00A0' );
} );
```

---

It is acceptable but I think it's tedious to use two filters to display correctly (imho) a price.
So I decided to override the currency filter using this way :
```
const originalCurrencyFilter = Vue.filter( "currency" );

const currencyFilterNewDef = function (
    symbol: string,
    separator: string,
    fractionCount: string,
    fractionSeparator: string,
    symbolPosition: string,
    symbolSpacing: string
) {
    return originalCurrencyFilter( symbol, separator, fractionCount, fractionSeparator, symbolPosition, symbolSpacing )
        .replace( /\s/g, '\u00A0' );
};

Vue.filter( "currency", currencyFilterNewDef );
 ```

The downside is that this is not the most maintainable solution but I'll stick with it for the moment.

---

I don't know if you should consider to add such an option to your library.
I'm not a typographer ;-)

I close the issue as I found a solution.
Thanks again !
