### ISSUE TITLE
Not usable with SSR since v2.2

### ISSUE THREAD

**Issue by Sopamo** [mazipan/vue-currency-filter#20]
It seems like the switch to webpack 4 made it so that this package doesn't work with Server Side Rendering any more, because in the dist file a window object is inserted, which doesn't exist in node applications.

**Comment by mazipan** [comment]
Hmmm, I think it's related with `umd` module that I choose ya ?
Will find the solution.

**Comment by mazipan** [comment]
Can you help me @Sopamo to validated this changes.
You can install newest version.
Hope it will solve this issue.

**Comment by Sopamo** [comment]
Thanks for answering so quickly!
The window issue is gone, but the filter isn't registered at all now. I built a small reproduction for you:

https://codesandbox.io/s/oom7p2y2y9

You can see in the console (in the bottom bar) that the currency filter isn't available.

**Comment by mazipan** [comment]
Hmmm, embarrassing 😅
I will try to find another solution

**Comment by benomas** [comment]
"Vue warn]: Failed to resolve filter: currency"
Same error over here

**Comment by mazipan** [comment]
Please downgrade to 2.2.0 first.
While I tried to find root cause.

**Comment by mazipan** [comment]
Can you try with version 2.2.4 @Niklv @benomas @Anatolie @Sopamo 

https://codesandbox.io/s/xvo87491vw

**Comment by Sopamo** [comment]
Yep, that fixed it. Thanks a lot!
