### ISSUE TITLE
Code Quality: Improve linting

### ISSUE THREAD

**Issue by dsfx3d** [mazipan/vue-currency-filter#209]
In the project, we are using local linting configurations for each package.

1. `eslint` in _demo_
2. `standardx` in _vue-currency-filter_

This heterogeneous structure doesn't feel right.

Would it make sense if instead of linting at the package level we configure linting at the global level?

**Proposal**

Let's configure ESLint at the global level so that all packages follow the same linting standards.

**Comment by dsfx3d** [comment]
I'm ready to make a PR for this. I mentioned this change in the comments of #205 but I wasn't able to find time to work on it because of work.

**Comment by mazipan** [comment]
Just update the linter to the root at https://github.com/mazipan/vue-currency-filter/commit/6756bdb87a2fed2225679e27cd964c0685b06783

**Comment by dsfx3d** [comment]
@mazipan can you also add prettier?

**Comment by mazipan** [comment]
Hmmm, lemme check

**Comment by mazipan** [comment]
Add here https://github.com/mazipan/vue-currency-filter/commit/a99ee81f53c2687e4964e60fe836977682ade0e1
