### ISSUE TITLE
Current state config of plugin

### ISSUE THREAD

**Issue by VIMHaos** [mazipan/vue-currency-filter#31]
How may I get current state config your plugin?

**Comment by mazipan** [comment]
For now, we can't.
but we will put this into our next improvement.

**Comment by VIMHaos** [comment]
hi, @mazipan
Yes please, thanks)

**Comment by mazipan** [comment]
You can update version to 3.2.0 then getting current global configs with

`this.$CurrencyFilter.getConfig()`

**Comment by VIMHaos** [comment]
Thank you @mazipan ,)
Have a nice day.

**Comment by iggyvanlith** [comment]
> You can update version to 3.2.0 then getting current global configs with
> 
> `this.$CurrencyFilter.getConfig()`
> 
> @VIMHaos

Would be nice to have these in the docs. This seems to be needed (the `setConfig()`) to have the currency update instantly when a user changes his currency settings.

**Comment by mazipan** [comment]
Ah, I already dropping this feature.
Since it's hard to achieve consistency from my latest approach.
Maybe need another perspective to solve this problem.
