### ISSUE TITLE
While using TypeScript: Could not find a declaration file for module 'vue-currency-filter'

### ISSUE THREAD

**Issue by antonio-valdez-arce** [mazipan/vue-currency-filter#34]
I get this error while using TypeScript in Vue.

Could not find a declaration file for module 'vue-currency-filter'. '/node_modules/vue-currency-filter/dist/vue-currency-filter.js' implicitly has an 'any' type.
  Try `npm install @types/vue-currency-filter` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-currency-filter';`

**Comment by mazipan** [comment]
I am not familiar with TypeScript, but PR are welcome @antonio-valdez-arce

**Comment by antonio-valdez-arce** [comment]
Hello @mazipan,
I investigated a little, and it turns out it would require some substantial refactoring, for instance, migrating you project to TypeScript, which it wouldn't make sense.

I managed to implement a workaround in my project instead, by following this article:
https://medium.com/@chris_72272/migrating-to-typescript-write-a-declaration-file-for-a-third-party-npm-module-b1f75808ed2

Thank you for your code!

I think this issue can be closed.

**Comment by DavidRouyer** [comment]
TypeScript doesn't require any migration at all.
You just have to write a [TypeScript definition file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html), put it in a **types** folder at the root of the repository and declare it in the **package.json** file.
You can take a look at the Vue.js repository: https://github.com/vuejs/vue/blob/dev/package.json#L9

**Comment by mazipan** [comment]
PR are always welcome
