### ISSUE TITLE
can initialize multiple configs

### ISSUE THREAD

**Issue by musman92** [mazipan/vue-currency-filter#41]
i need multiple configs, but currently we can use this plugin in one way

Vue.use(VueCurrencyFilter,
  {
    symbol : '$',
    thousandsSeparator: ',',
    fractionCount: 0,
    fractionSeparator: '.',
    symbolPosition: 'front',
    symbolSpacing: false
  })
Vue.use(VueCurrencyFilter,
  {
   name: 'abtestt', // like this
    symbol : '$',
    thousandsSeparator: ',',
    fractionCount: 2,
    fractionSeparator: '.',
    symbolPosition: 'front',
    symbolSpacing: false
  })
{{ v1 | currency}} //  1st filter works
{{ v1 | abtestt}} //  now 2nd one

**Comment by mazipan** [comment]
Yes, with current version it's not possible to do multiple instance.
Will try to find solutions for this, but maybe not for very fast response.

PR are very welcome for this issue 👏

**Comment by mazipan** [comment]
Close in [3.4.0](https://github.com/mazipan/vue-currency-filter/releases/tag/3.4.0)
