### ISSUE TITLE
npm files pointing incorrectly

### ISSUE THREAD

**Issue by ricardogobbosouza** [mazipan/vue-currency-filter#52]
All files are pointing to the min file, this is not correct and it is breaking.
When should it be:

```js
// main -> umd
// module -> cjs(commonjs)

"main": "dist/VueCurrencyFilter.js",
"module": "dist/VueCurrencyFilter.cjs.js"
```

https://github.com/mazipan/vue-currency-filter/commit/5bc7eabe5fd9c6b78e7f2d3de2eadbc2616550d7

**Comment by mazipan** [comment]
It's because now we only generate Umd files.

**Comment by ricardogobbosouza** [comment]
@mazipan 
This last version 3.4.1 is with error, mainly in nuxt, the 3.4.0 works perfectly.
From what I've tested, it's the minified file pointed.

**Comment by ricardogobbosouza** [comment]
```js
// plugins/currency-filter.js
import Vue from 'vue'
import VueCurrencyFilter from 'vue-currency-filter'

Vue.use(VueCurrencyFilter)
```

```js
// nuxt.config.js
export default {
    plugins: [
        '~/plugins/currency-filter'
    ]
}
```
```js
// package.json
{
    "private": true,
    "scripts": {
        "dev": "nuxt"
    },
    "dependencies": {
        "nuxt": "^2.6.2",
        "vue-currency-filter": "^3.4.1" // Not work
        "vue-currency-filter": "3.4.0" // It works
    }
}

**Comment by gijsroge** [comment]
@ricardogobbosouza could you try again with the latest version? I have a feeling you ran into the same issue as #53.

Also i suggest you follow the readme for Nuxt usage. https://github.com/mazipan/vue-currency-filter#usage-in-nuxtjs

**Comment by mazipan** [comment]
Follow this guide for Nuxt usage: https://github.com/mazipan/vue-currency-filter#usage-in-nuxtjs
