### ISSUE TITLE
Any chance you can publish a new release?

### ISSUE THREAD

**Issue by gijsroge** [mazipan/vue-currency-filter#56]
I don't want to sound pushy, but any chance you can publish a new release? Thanks!

**Comment by mazipan** [comment]
Published in `3.4.2`

**Comment by mazipan** [comment]
Help me to test ya @gijsroge

**Comment by gijsroge** [comment]
@mazipan works perfect! Thanks for the lightning fast responses 💯

**Comment by mazipan** [comment]
Thanks also for your help.
