### ISSUE TITLE
Show decimals only when necessary

### ISSUE THREAD

**Issue by cedriccouret** [mazipan/vue-currency-filter#59]
Hi,

would it be possible to show decimals only when needed? For example I want to display 1234,45$ but not 1234,00$. This one should be 1234$. I'd like to strip insignificant zeros.

Thanks.

**Comment by mazipan** [comment]
This is not common needed, because in term of currency we usually show fixed fraction count.
But maybe we can introduce new config for this needed.

You can also open pull request, if you think you can update the code by your self.
I will update when I have free time, today is weekend in Indonesia so I will slow response for this

**Comment by cedriccouret** [comment]
Thanks for your answer.

I managed to fix my issue by doing a simple String.replace with a regex. But integrating such a feature in your package would require to take a look at the bigger picture to make it work with a multiple locales (some use dots and other use commas). I won't have time for this but maybe someone in the community will.

Thanks again.

**Comment by benjaminwy** [comment]
In case it saves anybody 5 minutes, here's a little filter I wrote that handles my use case:

```
Vue.filter('stripZeros', function(value) {
    if (!value) return '';

    if (['.00', ',00'].includes(value.slice(-3))) {
        return value.slice(0, -3);
    }

    return value;
});
```
Usage: `{{ value | currency | stripZeros }}`

**Comment by Mweydert** [comment]
If this helps, I modify function of @benjaminwy using a regex to have something a bit more generic.
Especially to support input values that includes currency symbol.
```javascript
export const stripZeros = value => {
  if (!value) {
    return '';
  } else {
    return value.replace(/\.[0]+/, '');
  }
};
```
