### ISSUE TITLE
om sepertinya ada bug di symbolSpacing

### ISSUE THREAD

**Issue by ayrokid** [mazipan/vue-currency-filter#6]
Vue.use(VueCurrencyFilter,
    {
        symbol : '$',
        thousandsSeparator: '.',
        fractionCount: 0,
        fractionSeparator: ',',
        symbolPosition: 'front',
        symbolSpacing: false
    }
)

tapi di tampilan filternya masih belum jalan.

![screen shot 2017-11-07 at 7 12 31 pm](https://user-images.githubusercontent.com/5662089/32495000-63c477da-c3f6-11e7-8c90-e4fc48722ce2.png)

**Comment by mazipan** [comment]
Closed in new version
