### ISSUE TITLE
How to style symbol differently?

### ISSUE THREAD

**Issue by Youhan** [mazipan/vue-currency-filter#60]
Hi, I want to have a different `font-size` on the symbol and floating digits.
I am assuming to get this

`<span>$</span><span>999</span><span>.88</span>`
![image](https://user-images.githubusercontent.com/2191898/57631590-62b9c800-7565-11e9-837a-71063551b467.png)

Is this possible?

**Comment by mazipan** [comment]
For now, we can't do it.
Or maybe you can't do with static tag.

```html
<span>$</span>
<span>999 | currency({
  symbol: '',
  thousandsSeparator: '.',
  fractionCount: 0,
  fractionSeparator: '',
  symbolPosition: '',
  symbolSpacing: false
)
</span>
<span>your fraction</span>
```

**Comment by Youhan** [comment]
Thanks. 
Could we have that as a feature request?

**Comment by mazipan** [comment]
I don't think it can be implement in this library because this library stand for `filter` only.
The filter can not return HTML, it only for formatting string.
