### ISSUE TITLE
Cannot set thousands separator to '' or ' ' (space)

### ISSUE THREAD

**Issue by sedyshev-a** [mazipan/vue-currency-filter#7]
Hello!
Can you explain me what this line of code is doing:
`if(!thousandsSeparator || !isNaN(thousandsSeparator)) thousandsSeparator = '.'`

I want to set thousands separator to space (or empty string), but this condition does not allow to do this

**Comment by mazipan** [comment]
I won't user set `thousandsSeparator` with any number.
If it's number it will set to default.

**Comment by mazipan** [comment]
I already checked in demo page https://mazipan.github.io/vue-currency-filter/ and work well

**Comment by mazipan** [comment]
Oh I see,

It is because this code `!thousandsSeparator`
Maybe you can create pull request to delete this line

**Comment by Scalpel78** [comment]
We have the same problem, we also want to set thousandSeparator to ' '.
