### ISSUE TITLE
Cannot set thousand separator to space

### ISSUE THREAD

**Issue by oharan** [mazipan/vue-currency-filter#9]
I'm having a small problem using your filter with French Canadian. French Canadian uses thousand separator of space, but your filter is setting it to the default because it thinks an empty space is a number.

**Comment by oharan** [comment]
` if(!_isUndefined(thousandsSeparator) && !isNaN(thousandsSeparator)) thousandsSeparator = '.'`

This is the line. If you do !isNaN(parseInt(thousandsSeparator)) it works with a space.

**Comment by mazipan** [comment]
You can create pull request then, feel free to correcting the code.
